# Generated by Django 4.2.6 on 2023-11-12 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modelo',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='auto',
            name='numero_de_ruedas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='patente',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
