# Generated by Django 4.2.6 on 2023-11-12 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Auto', '0002_auto_cliente_alter_auto_marca_alter_auto_modelo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='cliente',
        ),
        migrations.AddField(
            model_name='auto',
            name='propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='Cliente.cliente'),
        ),
    ]
