# Generated by Django 4.2.6 on 2023-11-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0003_remove_auto_cliente_auto_propietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_de_nacimiento', models.DateField()),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
