# Generated by Django 4.2.6 on 2023-11-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursal', '0001_initial'),
        ('Auto', '0004_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('apertura', models.DateField()),
                ('gerente', models.CharField(max_length=100)),
                ('fono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='Sucursal.sucursal')),
            ],
        ),
    ]
